(() => {
  const TYPES={party:'parties',ideology:'ideologies',figure:'figures',user:'users'};
  const LABELS={party:{intro:'Wprowadzenie',history:'Historia',program:'Program',politicians:'Politycy'},ideology:{intro:'Wprowadzenie',history:'Historia',values:'Wartości',impact:'Wpływ',representatives:'Przedstawiciele',readings:'Lektury',terms:'Pojęcia'},figure:{intro:'Wprowadzenie',history:'Historia',views:'Poglądy',publicActivity:'Działalność publiczna',readings:'Lektury',legacy:'Dziedzictwo',quotes:'Cytaty'}};
  let db,active='party',selectedTags=new Set();const $=s=>document.querySelector(s);const text=v=>typeof v==='string'&&v.trim();
  const profiles=()=>db?.[TYPES[active]]||[];
  function img(profile,className=''){return profile.logo?`<img class="${className}" src="${profile.logo}" alt="" loading="lazy">`:`<div class="profile-placeholder ${className}">${(profile.name||'?').trim()[0]||'?'}</div>`}
  function renderTags(){const tags=[...new Set(profiles().flatMap(p=>Array.isArray(p.tags)?p.tags:[]))].sort((a,b)=>a.localeCompare(b,'pl'));$('#album-tags').innerHTML=tags.map(tag=>`<button type="button" data-tag="${tag.replaceAll('&','&amp;').replaceAll('"','&quot;')}" class="${selectedTags.has(tag)?'active':''}">${tag}</button>`).join('');$('#album-tags').querySelectorAll('button').forEach(b=>b.onclick=()=>{selectedTags.has(b.dataset.tag)?selectedTags.delete(b.dataset.tag):selectedTags.add(b.dataset.tag);renderTags();renderGrid()})}
  function filtered(){const search=$('#album-search').value.trim().toLocaleLowerCase('pl'),onlyImage=$('#album-with-image').checked;return profiles().filter(p=>{const hay=[p.name,p.description,p.country,...(p.tags||[]),...Object.values(p.infobox||{})].join(' ').toLocaleLowerCase('pl');return (!search||hay.includes(search))&&(!onlyImage||p.logo)&&[...selectedTags].every(t=>(p.tags||[]).includes(t))}).sort((a,b)=>$('#album-sort').value==='type'?String(a.type).localeCompare(String(b.type)):a.name.localeCompare(b.name,'pl'))}
  function renderGrid(){const list=filtered();$('#album-count').textContent=`${list.length} ${list.length===1?'profil':'profili'} w kategorii`;$('#album-grid').innerHTML=list.map(p=>`<button class="profile-card" type="button" data-id="${encodeURIComponent(p.id)}">${img(p)}<strong>${p.name}</strong><small>${(p.tags||[]).slice(0,2).join(' · ')}</small></button>`).join('')||'<p>Brak profili spełniających wybrane kryteria.</p>';$('#album-grid').querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>openProfile(decodeURIComponent(b.dataset.id)))}
  function titleCase(key){return key.replace(/([A-Z])/g,' $1').replace(/^./,x=>x.toUpperCase())}
  function openProfile(id){const p=Object.values(TYPES).flatMap(key=>db[key]||[]).find(x=>x.id===id||x.key===id||x.name===id);if(!p)return;const sections=LABELS[p.type]||{};const blocks=Object.entries(sections).filter(([key])=>text(p[key])).map(([key,label])=>`<section class="profile-block"><h2>${label}</h2><p>${p[key]}</p></section>`).join('');const box=Object.entries(p.infobox||{}).filter(([,value])=>value!==null&&value!==undefined&&String(value).trim()!=='').map(([key,value])=>`<dt>${titleCase(key)}</dt><dd>${String(value)}</dd>`).join('');$('#profile-view').className='profile-full';$('#profile-view').innerHTML=`<main class="profile-main"><header class="profile-hero"><span class="profile-type">${p.type}</span><h1>${p.name}</h1>${text(p.description)?`<p>${p.description}</p>`:''}</header>${blocks||'<p>Ten profil nie ma jeszcze rozwiniętych sekcji.</p>'}</main><aside class="profile-infobox">${img(p)}${box?`<dl>${box}</dl>`:''}</aside>`;location.hash=encodeURIComponent(p.id);$('#profile-dialog').showModal()}
  function setType(type){active=type;selectedTags.clear();document.querySelectorAll('[data-type]').forEach(b=>b.classList.toggle('active',b.dataset.type===type));renderTags();renderGrid()}
  document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>setType(b.dataset.type));['#album-search','#album-with-image','#album-sort'].forEach(s=>$(s).addEventListener(s==='#album-search'?'input':'change',renderGrid));$('.dialog-close').onclick=()=>{$('#profile-dialog').close();history.replaceState(null,'',location.pathname)};$('#profile-dialog').addEventListener('click',e=>{if(e.target===$('#profile-dialog'))$('#profile-dialog').close()});
  fetch('political_profiles.json').then(r=>r.json()).then(data=>{db=data;const id=decodeURIComponent(location.hash.slice(1));const profile=Object.values(TYPES).flatMap(key=>db[key]||[]).find(p=>p.id===id||p.key===id||p.name===id);if(profile){active=profile.type;setType(active);openProfile(profile.id)}else setType(active)}).catch(()=>{$('#album-grid').textContent='Nie udało się wczytać bazy profili.'});
})();
