/* Shared UI state: one theme and independently scoped compass filters. */
(() => {
  'use strict';
  const filterState={party:new Set(),figure:new Set()};
  const dark=()=>localStorage.getItem('theme')==='dark'||(!localStorage.getItem('theme')&&matchMedia('(prefers-color-scheme:dark)').matches);
  function theme(){document.documentElement.classList.toggle('dark',dark());document.body.classList.toggle('dark',dark());document.querySelectorAll('#theme-toggle,#floating-theme-toggle,#hub-theme-toggle').forEach(b=>b.textContent=dark()?'☀️':'🌙');}
  function bindTheme(){theme();document.querySelectorAll('#floating-theme-toggle,#hub-theme-toggle').forEach(btn=>btn.addEventListener('click',()=>{localStorage.setItem('theme',document.body.classList.contains('dark')?'light':'dark');theme();}));}
  function tagsFor(items){return [...new Set((items||[]).flatMap(x=>x.tags||[]))].sort((a,b)=>String(a).localeCompare(String(b),'pl'));}
  function filterPanel(type,items){const root=document.getElementById('compass-tag-filters');if(!root)return;let section=root.querySelector(`[data-filter-kind="${type}"]`);if(!section){section=document.createElement('section');section.className='overlay-filter-system';section.dataset.filterKind=type;root.append(section);}section.replaceChildren();const heading=document.createElement('strong');heading.textContent=type==='party'?'Filtry partii':'Filtry figur';section.append(heading);const tags=tagsFor(items);if(!tags.length){section.append(' Brak tagów.');return;}const list=document.createElement('div');list.className='tag-options';tags.forEach(tag=>{const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.checked=filterState[type].has(tag);input.onchange=()=>{input.checked?filterState[type].add(tag):filterState[type].delete(tag);window.NeoOverlayRefresh?.();};label.append(input,document.createTextNode(` ${tag}`));list.append(label);});section.append(list);}
  function matches(item,type){return [...filterState[type]].every(tag=>(item.tags||[]).includes(tag));}
  async function coordinateFor(profile,type){if(type!=='figure')return getEntityCoordinates(profile.key||profile.name,type);const rows=parseExportCode(profile.exportCode||'').filter(x=>!x.noteOnly&&x.answerData);if(!rows.length)return null;const values=buildUserValuesMap(computeScoresForAnswers(rows,currentScoringMode).pairResults);const point=computeCoordinatesFromValues(values,currentCompassMode,currentCreativeConfig);return {x:point.x,y:point.y};}
  async function renderOverlays(instance){if(!instance?.clearOverlays||!config)return;instance.clearOverlays();const enabled={party:document.getElementById('toggle-parties')?.checked,ideology:document.getElementById('toggle-ideologies')?.checked,user:document.getElementById('toggle-users')?.checked,figure:document.getElementById('toggle-figures')?.checked};const groups={party:config.parties||[],ideology:config.ideologies||[],user:config.users||[],figure:politicalProfiles?.figures||[]};for(const [type,items] of Object.entries(groups)){if(!enabled[type])continue;for(const profile of items){if((type==='party'||type==='figure')&&!matches(profile,type))continue;const point=await coordinateFor(profile,type);if(!point)continue;const logo=profile.logo||(type==='party'?getPartyLogoUrl(profile.name):type==='ideology'?getIdeologyLogoUrl(profile.name):profile.avatar?`images/IUsers/${profile.avatar}`:'images/ALogo.svg');instance.addOverlay(logo,point.x,point.y,type,profile.name,profile.description||'');}}}
  function installOverlays(){window.NeoOverlayRefresh=()=>{renderOverlays(window.compassInstance);renderOverlays(window.modalCompassInstance);};const original=window.loadOverlays;window.loadOverlays=async(_parties,_ideologies,instance)=>renderOverlays(instance);['toggle-parties','toggle-ideologies','toggle-users','toggle-figures'].forEach(id=>document.getElementById(id)?.addEventListener('change',window.NeoOverlayRefresh));const watch=setInterval(()=>{if(!config||!politicalProfiles)return;clearInterval(watch);filterPanel('party',config.parties);filterPanel('figure',politicalProfiles.figures);window.NeoOverlayRefresh();},100);}
  function timeline(){const root=document.getElementById('timeline-shift-controls'),input=document.getElementById('figure-year-filter');if(!root||!input)return;const adjust=n=>{const raw=input.value.trim(),match=raw.match(/^(\d{1,4})(?:\s*-\s*(\d{1,4}))?$/);const a=(match?Number(match[1]):new Date().getFullYear())+n,b=match?.[2]?Number(match[2])+n:null;input.value=b?`${a}-${b}`:String(a);input.dispatchEvent(new Event('input',{bubbles:true}));};[-10,-5,-1].forEach(n=>{const b=document.createElement('button');b.type='button';b.textContent=`← ${Math.abs(n)} ${Math.abs(n)===1?'rok':'lat'}`;b.onclick=()=>adjust(n);root.append(b);});const custom=document.createElement('input');custom.type='number';custom.placeholder='± lata';custom.setAttribute('aria-label','Własne przesunięcie w latach');custom.onchange=()=>{adjust(Number(custom.value)||0);custom.value='';};root.append(custom);[10,5,1].forEach(n=>{const b=document.createElement('button');b.type='button';b.textContent=`+${n} ${n===1?'rok':'lat'} →`;b.onclick=()=>adjust(n);root.append(b);});}
  function developerLink(){const host=document.querySelector('.hub-primary-actions');if(!host)return;const button=document.createElement('a');button.href='dependency-map.html';button.className='hub-text-link developer-map-link';button.textContent='Mapa zależności pytań →';button.hidden=!window.DEV_MODE;host.append(button);setInterval(()=>button.hidden=!window.DEV_MODE,400);}
  let installed=false;function start(){if(installed)return;installed=true;installOverlays();timeline();}window.addEventListener('neoAutystykConfigReady',start);document.addEventListener('DOMContentLoaded',()=>{bindTheme();developerLink();if(window.config||typeof config!=='undefined')start();});
})();
