(async function () {
  'use strict';
  const state={zoom:1,panX:0,panY:0,tags:new Set(),profiles:null,data:null,friends:[],pointer:new Map(),lastPinch:null};
  const stage=document.getElementById('compass-stage'), grid=document.getElementById('compass-grid'), markers=document.getElementById('compass-markers'), details=document.getElementById('marker-details');
  const catalog={figures:{'Zawód / dziedzina':['Filozof','Ekonomista','Polityk'],'Rola / urząd':['Autokrata','Prezydent','Premier'],'Narodowość':['Amerykanin','Brytyjczyk'],Status:['Żyje','Martwy'],Płeć:['Kobieta','Mężczyzna'],'Okres życia':['XVII wiek','XVIII wiek','XIX wiek','XX wiek','XXI wiek'],Ideologia:['Liberalizm','Libertarianizm','Konserwatyzm','Socjalizm','Komunizm','Faszyzm','Nacjonalizm','Monarchizm','Anarchizm','Republikanizm']},parties:{Status:['Parlamentarne','Pozaparlamentarne']},ideologies:{Kierunek:['Lewicowe','Prawicowe','Centrowe','Liberalne','Konserwatywne','Socjalistyczne','Libertariańskie','Anarchistyczne','Monarchistyczne']}};
  const answerNorm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim();
  function applyTheme(){const dark=localStorage.getItem('theme')==='dark'||(!localStorage.getItem('theme')&&matchMedia('(prefers-color-scheme: dark)').matches);document.body.classList.toggle('dark',dark);document.getElementById('compass-theme-toggle').textContent=dark?'☀️':'🌙'}
  document.getElementById('compass-theme-toggle').onclick=()=>{localStorage.setItem('theme',document.body.classList.contains('dark')?'light':'dark');applyTheme()};applyTheme();
  function parseCode(raw){const map=new Map();for(const line of String(raw||'').split(/\r?\n/)){let m=line.match(/^\s*(?:\d+\.\s*.*?\s*)?\[id:(\d+)\]\s*:\s*\((.*?)\)\s*;?\s*$/i)||line.match(/^\s*(\d+)\s*:\s*\((.*?)\)\s*;?\s*$/);if(m)map.set(Number(m[1]),m[2].trim())}return map}
  function answerFor(q,label){const n=answerNorm(label);if(['brak odpowiedzi','pomin','pomin pytanie','skip'].includes(n))return q.answers.find(a=>Number(a.value)===0);return q.answers.find(a=>answerNorm(a.label)===n)}
  function scores(code){const answers=parseCode(code), values=new Map();state.data.pairsOfValues.forEach(p=>{values.set(p.left,{sum:0,max:0});values.set(p.right,{sum:0,max:0})});for(const q of state.data.questions){const a=answerFor(q,answers.get(Number(q.id)));if(!a||!Number(a.value))continue;const factor=Math.abs(Number(a.value))*Number(q.weight||1);for(const value of a.values_for||[]){const r=values.get(value);if(r){r.sum+=factor;r.max+=1.5*Number(q.weight||1)}}for(const value of a.values_against||[]){const r=values.get(value);if(r){r.sum-=factor;r.max+=1.5*Number(q.weight||1)}}}const pair=new Map();for(const p of state.data.pairsOfValues){const l=values.get(p.left),r=values.get(p.right),max=(l?.max||0)+(r?.max||0);const left=max?Math.max(0,Math.min(100,((l.sum-r.sum)+max)/(2*max)*100)):50;pair.set(p.left,{left,right:100-left})}const lookup=(negative,positive)=>{for(const p of state.data.pairsOfValues){const s=pair.get(p.left);if(p.left===negative&&p.right===positive)return{s:s.left,t:s.right};if(p.left===positive&&p.right===negative)return{s:s.right,t:s.left}}return{s:50,t:50}};const xpairs=[['Własność kolektywna','Własność prywatna',1.5],['Planowanie','Rynek',1]],ypairs=[['Samoregulacja','Regulacja instytucjonalna',1],['Samoorganizacja','Etatyzm',1.75],['Decentralizacja','Centralizacja',1],['Ograniczenie władzy','Absolutyzm władzy',1.75],['Różnorodność norm','Uniformizacja norm',1],['Minimalizacja granic','Kontrola granic',.5],['Wolność ekspresji','Cenzura',1],['Autonomia','Heteronomia',2],['Antypaternalizm','Paternalizm',1.5],['Kontraktualizm','Organicyzm',1.5],['Dobrowolność wspólnoty','Obowiązkowość wspólnoty',1.5],['Desakralizacja autorytetu','Sakralizacja autorytetu',1.75]];const coord=list=>{let n=0,d=0;for(const [a,b,w]of list){const z=lookup(a,b);n+=(z.t-z.s)*w;d+=100*w}return d?Math.max(-10,Math.min(10,n/d*10)):0};return{x:coord(xpairs),y:coord(ypairs)}}
  function valid(profile){return [...state.tags].every(tag=>(profile.tags||[]).includes(tag))}
  function profiles(){return [['user',state.profiles.users||[]],['figure',state.profiles.figures||[]],['party',state.profiles.parties||[]],['ideology',state.profiles.ideologies||[]]].flatMap(([kind,list])=>list.map(p=>({...p,kind}))).filter(valid)}
  function pos(x,y){const r=stage.getBoundingClientRect(),u=Math.min(r.width,r.height)/20*state.zoom;return{x:r.width/2+state.panX+x*u,y:r.height/2+state.panY-y*u,unit:u}}
  function render(){const r=stage.getBoundingClientRect(),o=pos(0,0);stage.style.setProperty('--unit',`${o.unit}px`);stage.style.setProperty('--origin-x',`${o.x}px`);stage.style.setProperty('--origin-y',`${o.y}px`);markers.innerHTML='';const enabled=new Set([...document.querySelectorAll('[data-kind]:checked')].map(x=>x.dataset.kind));const own=scores(sessionStorage.getItem('neoAutystykExportCode')||localStorage.getItem('neoAutystykExportCode')||'');addMarker({name:'Twój wynik',description:`X: ${own.x.toFixed(2)}, Y: ${own.y.toFixed(2)}`,x:own.x,y:own.y,kind:'self'});for(const p of profiles())if(enabled.has(p.kind)){const c=scores(p.exportCode);addMarker({...p,x:c.x,y:c.y})}for(const p of state.friends)addMarker(p);document.getElementById('zoom-value').textContent=`${Math.round(state.zoom*100)}%`}
  function addMarker(p){const q=pos(p.x,p.y);if(q.x<-80||q.y<-80||q.x>stage.clientWidth+80||q.y>stage.clientHeight+80)return;const el=document.createElement('button');el.type='button';el.className=`compass-marker ${p.kind}`;el.style.left=`${q.x}px`;el.style.top=`${q.y}px`;if(p.logo){const img=document.createElement('img');img.src=p.logo;img.alt='';el.append(img)}else el.textContent=p.kind==='self'?'●':'•';const label=document.createElement('span');label.className='marker-label';label.textContent=`${p.name} (${p.x.toFixed(2)}, ${p.y.toFixed(2)})`;label.hidden=state.zoom<1.4;el.append(label);el.onclick=e=>{e.stopPropagation();details.hidden=false;details.innerHTML=`<strong>${p.name}</strong><small>X: ${p.x.toFixed(3)}, Y: ${p.y.toFixed(3)}</small><p>${p.description||'Brak opisu.'}</p>`};markers.append(el)}
  function filters(){const root=document.getElementById('tag-filters');for(const [kind,groups]of Object.entries(catalog))for(const [title,tags]of Object.entries(groups)){const box=document.createElement('div');box.className='tag-group';box.innerHTML=`<strong>${kind==='figures'?'Figury':kind==='parties'?'Partie':'Ideologie'} · ${title}</strong><div class="tag-options"></div>`;const list=box.lastElementChild;for(const tag of tags){const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.onchange=()=>{input.checked?state.tags.add(tag):state.tags.delete(tag);render()};label.append(input,document.createTextNode(` ${tag}`));list.append(label)}root.append(box)}}
  function zoomAt(factor,cx,cy){const before=pos(0,0);state.zoom=Math.max(.2,state.zoom*factor);const after=pos(0,0);state.panX+=cx-(after.x-(before.x-cx));state.panY+=cy-(after.y-(before.y-cy));render()}
  stage.addEventListener('wheel',e=>{e.preventDefault();const r=stage.getBoundingClientRect();zoomAt(e.deltaY<0?1.15:1/1.15,e.clientX-r.left,e.clientY-r.top)},{passive:false});stage.addEventListener('pointerdown',e=>{stage.setPointerCapture(e.pointerId);state.pointer.set(e.pointerId,{x:e.clientX,y:e.clientY})});stage.addEventListener('pointermove',e=>{if(!state.pointer.has(e.pointerId))return;const old=state.pointer.get(e.pointerId);state.pointer.set(e.pointerId,{x:e.clientX,y:e.clientY});const pts=[...state.pointer.values()];if(pts.length===1){state.panX+=e.clientX-old.x;state.panY+=e.clientY-old.y;render()}else if(pts.length===2){const d=Math.hypot(pts[0].x-pts[1].x,pts[0].y-pts[1].y);if(state.lastPinch)zoomAt(d/state.lastPinch,stage.clientWidth/2,stage.clientHeight/2);state.lastPinch=d}});['pointerup','pointercancel'].forEach(t=>stage.addEventListener(t,e=>{state.pointer.delete(e.pointerId);state.lastPinch=null}));stage.onclick=()=>details.hidden=true;window.addEventListener('resize',render);document.querySelectorAll('[data-kind]').forEach(x=>x.onchange=render);document.getElementById('reset-view').onclick=()=>{state.zoom=1;state.panX=state.panY=0;render()};
  document.getElementById('friend-import').onclick=()=>{const raw=document.getElementById('friend-code').value.trim(),name=document.getElementById('friend-name').value.trim()||`Znajomy ${state.friends.length+1}`,msg=document.getElementById('friend-message'),parsed=parseCode(raw);if(!raw||!parsed.size){msg.textContent='Nie udało się odczytać kodu. Wczytaj plik lub wklej pełny kod eksportu z identyfikatorami [id:…].';return}const validAnswers=[...parsed].filter(([id,label])=>state.data.questions.some(q=>Number(q.id)===id&&answerFor(q,label))).length;if(!validAnswers){msg.textContent='Kod został odczytany, ale nie zawiera rozpoznanych odpowiedzi.';return}const c=scores(raw);state.friends.push({name,description:`Zaimportowany znajomy · ${validAnswers} odpowiedzi`,x:c.x,y:c.y,kind:'friend'});msg.textContent=`Dodano ${name}: ${validAnswers} odpowiedzi, X ${c.x.toFixed(2)}, Y ${c.y.toFixed(2)}.`;document.getElementById('friend-code').value='';render()};
  try{const [d,p]=await Promise.all([fetch('data.json').then(r=>r.json()),fetch('political_profiles.json').then(r=>r.json())]);state.data=d;state.profiles=p;filters();document.getElementById('compass-status').textContent='Wynik i nakładki są gotowe.';render()}catch(e){document.getElementById('compass-status').textContent='Nie udało się wczytać danych kompasu.';console.error(e)}
})();
