(() => {
  'use strict';
  const $=id=>document.getElementById(id), state={nodes:[],edges:[],zoom:1,x:0,y:0,drag:null};
  const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const requirements=v=>Array.isArray(v)?v.flat(Infinity).map(Number).filter(Number.isFinite):[];
  function theme(){const d=localStorage.getItem('theme')==='dark'||(!localStorage.getItem('theme')&&matchMedia('(prefers-color-scheme:dark)').matches);document.body.classList.toggle('dark',d);$('map-theme').textContent=d?'☀️':'🌙';}
  function render(){const c=$('map-canvas');c.style.transform=`translate(${state.x}px,${state.y}px) scale(${state.zoom})`;const edges=state.edges.map(e=>`<svg class="map-edge"><line x1="${e.a.x+105}" y1="${e.a.y+38}" x2="${e.b.x}" y2="${e.b.y+38}"></line><text x="${(e.a.x+e.b.x+105)/2}" y="${(e.a.y+e.b.y)/2+30}">${e.kind}</text></svg>`).join('');const nodes=state.nodes.map(n=>`<button class="map-node ${n.conditional?'conditional':''}" style="left:${n.x}px;top:${n.y}px" data-id="${n.id}"><b>#${n.id}</b><span>${esc(n.text)}</span></button>`).join('');c.innerHTML=edges+nodes;c.querySelectorAll('.map-node').forEach(n=>n.onclick=()=>focus(+n.dataset.id));}
  function focus(id){const n=state.nodes.find(x=>x.id===id);if(!n)return;state.x=Math.max(30,innerWidth*.55-n.x*state.zoom);state.y=Math.max(30,innerHeight*.42-n.y*state.zoom);const incoming=state.edges.filter(e=>e.b.id===id),outgoing=state.edges.filter(e=>e.a.id===id);$('map-details').innerHTML=`<strong>#${n.id}</strong><p>${esc(n.text)}</p><p><b>Aktywowane przez:</b> ${incoming.length?incoming.map(e=>`#${e.a.id} → ${e.kind}`).join('<br>'):'—'}</p><p><b>Aktywuje:</b> ${outgoing.length?outgoing.map(e=>`#${e.b.id} → ${e.kind}`).join('<br>'):'—'}</p>`;render();}
  async function load(){try{const manifest=await fetch('data-parts/manifest.json').then(r=>r.json());const parts=await Promise.all(manifest.parts.map(p=>fetch(p.file).then(r=>r.json())));const qs=parts.flatMap(p=>p.questions||[]), ids=new Set(qs.map(q=>+q.id)), conditional=new Map((manifest.conditionalQuestions||[]).map(x=>[+x.id,x]));state.nodes=qs.map((q,i)=>({id:+q.id,text:q.text,conditional:conditional.has(+q.id),x:(i%5)*235,y:Math.floor(i/5)*100}));const node=id=>state.nodes.find(n=>n.id===id);conditional.forEach((c,id)=>{requirements(c.require_yes).filter(ids.has,ids).forEach(source=>state.edges.push({a:node(source),b:node(id),kind:'wymaga za'}));requirements(c.require_no).filter(ids.has,ids).forEach(source=>state.edges.push({a:node(source),b:node(id),kind:'wymaga przeciw'}));});$('map-empty').hidden=true;render();$('map-search').oninput=e=>{const q=e.target.value.toLowerCase(),found=state.nodes.filter(n=>`${n.id} ${n.text}`.toLowerCase().includes(q)).slice(0,20);$('map-results').innerHTML=found.map(n=>`<button data-id="${n.id}">#${n.id} ${esc(n.text)}</button>`).join('');$('map-results').querySelectorAll('button').forEach(b=>b.onclick=()=>focus(+b.dataset.id));};}catch(e){console.error(e);$('map-empty').textContent='Nie udało się wczytać grafu.';}}
  const v=$('map-viewport');v.onpointerdown=e=>{state.drag={x:e.clientX,y:e.clientY};v.setPointerCapture(e.pointerId);};v.onpointermove=e=>{if(!state.drag)return;state.x+=e.clientX-state.drag.x;state.y+=e.clientY-state.drag.y;state.drag={x:e.clientX,y:e.clientY};render();};v.onpointerup=()=>state.drag=null;v.onwheel=e=>{e.preventDefault();state.zoom=Math.max(.25,Math.min(1.8,state.zoom*(e.deltaY<0?1.12:.89)));render();};$('map-theme').onclick=()=>{localStorage.setItem('theme',document.body.classList.contains('dark')?'light':'dark');theme();};theme();load();
})();
